CREATE TABLE IF NOT EXISTS ao3_urls (
    id INTEGER PRIMARY KEY NOT NULL,
    url VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS songs (
    name VARCHAR(50) PRIMARY KEY NOT NULL,
    aliases VARCHAR(512),
    ao3_id INTEGER NOT NULL UNIQUE,
    FOREIGN KEY(ao3_id) REFERENCES ao3_urls(id)
);
