//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fandoms")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fics_fandoms::Entity")]
    FicsFandoms,
}

impl Related<super::fics_fandoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FicsFandoms.def()
    }
}

impl Related<super::fics::Entity> for Entity {
    fn to() -> RelationDef {
        super::fics_fandoms::Relation::Fics.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::fics_fandoms::Relation::Fandoms.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
