//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fics_fandoms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub fic_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub fandom_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fandoms::Entity",
        from = "Column::FandomId",
        to = "super::fandoms::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fandoms,
    #[sea_orm(
        belongs_to = "super::fics::Entity",
        from = "Column::FicId",
        to = "super::fics::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Fics,
}

impl Related<super::fandoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fandoms.def()
    }
}

impl Related<super::fics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
