//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author_user_id: i32,
    pub title: String,
    pub phoenix_song_book: Option<i32>,
    pub phoenix_song_chapter: Option<i32>,
    pub is_phoenix_rocktail: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fics_fandoms::Entity")]
    FicsFandoms,
    #[sea_orm(has_many = "super::urls::Entity")]
    Urls,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::fics_fandoms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FicsFandoms.def()
    }
}

impl Related<super::urls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Urls.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::fandoms::Entity> for Entity {
    fn to() -> RelationDef {
        super::fics_fandoms::Relation::Fandoms.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::fics_fandoms::Relation::Fics.def().rev())
    }
}

impl Related<super::fic_platforms::Entity> for Entity {
    fn to() -> RelationDef {
        super::urls::Relation::FicPlatforms.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::urls::Relation::Fics.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
