//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fics")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author_user_id: i32,
    pub platform_id: i32,
    pub title: String,
    pub url: String,
    pub phoenix_song_book: Option<i32>,
    pub phoenix_song_chapter: Option<i32>,
    pub is_phoenix_rocktail: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::fic_platforms::Entity",
        from = "Column::PlatformId",
        to = "super::fic_platforms::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FicPlatforms,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorUserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::fic_platforms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FicPlatforms.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
