//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::fic_platforms::Entity as FicPlatforms;
pub use super::fics::Entity as Fics;
pub use super::users::Entity as Users;
pub use super::writing_prompts::Entity as WritingPrompts;
