//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub discord_id: String,
    pub birthday_month: Option<i32>,
    pub birthday_day: Option<i32>,
    pub last_love_spam: Option<DateTimeUtc>,
    pub time_zone: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::fics::Entity")]
    Fics,
}

impl Related<super::fics::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Fics.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
